repos:
  - repo: local
    hooks:
      - id: just-fast-check
        name: just fast-check
        entry: just fast-check
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: just-check
        name: just check
        entry: just check
        language: system
        pass_filenames: false
        stages: [pre-push]
